ROOT_DIR: .
DATA_DIR: ../data/200_patients/yolo26m/200_middle7

IMG_SIZE: 224
BATCH_SIZE: 64
NUM_WORKERS: 8

LR: 0.00001
WEIGHT_DECAY: 0.001
NUM_EPOCH: 100
DROPOUT: 0.3


SEED: 42
PATIENCE: 6
MIN_DELTA: 0.0001

TOP_K: 3
USE_AMP: true

MODE: min 
AGG: mean # mean, max, topk_mean, p90, p95, median

MODEL_WEIGHT: DEFAULT
POS_WEIGHT: 1.06

MEAN: [0.485, 0.456, 0.406]
STD: [0.229, 0.224, 0.225]
