ROOT_DIR: .
DATA_DIR: ../data/200_patients/200_middle7

IMG_SIZE: 224
BATCH_SIZE: 64
NUM_WORKERS: 8

LR: 0.0001
WEIGHT_DECAY: 0.0001
NUM_EPOCH: 100

SEED: 42
PATIENCE: 15
MIN_DELTA: 0.0001

TOP_K: 3
USE_AMP: true

MODE: min 
AGG: mean # mean, max, topk_mean, p90, p95, median

MODEL_WEIGHT: DEFAULT